// This file is auto-generated by the FAQ migration script

export const allFaqsData = [
  {
    id: "section-1",
    title: "AI Research FAQs",
    questions: [

  { q: "Why doesn't Rheole focus on Large Language Models (LLMs)?", a: "LLMs are exceptional at generating language, but they lack an inherent, grounded understanding of physical reality. Our research focuses on Spatial Intelligence—giving machines the ability to understand geometry, physics, context, and movement. Language is just one interface to that deeper understanding." },
  { q: "How is Ambient Intelligence different from General AI?", a: "Artificial General Intelligence (AGI) seeks to replicate human-level cognition across all domains. Ambient Intelligence is narrower but deeper; it seeks to perfectly understand and assist within the physical and contextual constraints of a user's immediate environment, without requiring conscious interaction." },
  { q: "Do you train your own foundation models?", a: "Yes, but they are Spatial Foundation Models. Instead of being trained purely on internet text, they are trained on vast, anonymized datasets of movement, environmental conditions, urban topology, and temporal rhythms to build a fundamental understanding of physical space." },
  { q: "How do you define 'Intent'?", a: "Intent is the underlying human goal. A query is 'Find a restaurant.' The intent might be 'I need a quiet place to close a business deal in the next 30 minutes.' Our research focuses on decoding the latter from minimal explicit input." },
  { q: "What is 'Explainable AI' in a spatial context?", a: "It means the AI must justify its decisions. If it reroutes you, it should provide a reason: 'Heavy pedestrian traffic detected ahead.' This transparency is non-negotiable for building trust in spatial systems." },
  { q: "How do you mitigate bias in spatial algorithms?", a: "Spatial bias is a significant risk (e.g., routing algorithms avoiding certain neighbourhoods due to flawed historical data). We actively research algorithmic fairness, ensuring our models do not reinforce systemic inequalities or artificially isolate communities." },
  { q: "What role does privacy play in your research?", a: "Privacy is the constraint that drives our innovation. We do not research how to collect more personal data; we research how to infer deep context using less data, relying heavily on edge computing and aggregated, anonymized environmental signals." },
  { q: "Are you trying to automate urban planning?", a: "No. We are building tools to augment urban planners. Our 'Urban Cognition' research provides planners with unprecedented insights into how citizens actually use physical spaces, allowing them to make more human-centric design decisions." },
  { q: "Why is 'Curiosity' a research topic?", a: "Algorithms naturally optimize for convenience, which can lead to 'spatial echo chambers' where users only visit familiar places. We research how AI can safely introduce serendipity and encourage users to explore new, diverse aspects of their cities." },
  { q: "What happens when the AI is wrong?", a: "Failure modes are a core research focus. We design systems that fail gracefully, clearly communicating uncertainty to the user and seamlessly transferring control back to human judgement without causing distress or danger." },
  { q: "How does weather affect your models?", a: "Weather is a primary contextual modifier. It changes human intent instantly. Our models treat weather not as an external variable, but as a foundational layer of the physical reality they are trying to understand." },
  { q: "What is the timeline for Ambient Spatial Intelligence?", a: "It is an incremental evolution, not a single breakthrough. We are already deploying early components (like contextual routing), but the fully realized vision of invisible, ambient assistance is a decade-long research trajectory." },
  { q: "Do you publish your research?", a: "Yes. We believe in open scientific discourse. While some proprietary algorithms remain internal, we regularly publish our findings on algorithmic fairness, spatial modeling, and privacy-preserving techniques." },
  { q: "How does human psychology influence your work?", a: "Deeply. You cannot build spatial intelligence without understanding how humans perceive space. We collaborate closely with behavioural psychologists to ensure our systems align with natural human cognitive patterns." },
  { q: "Can AI truly understand 'Context'?", a: "It can understand the mathematical representation of context (time + location + weather + history). Our research aims to bridge the gap between that mathematical state and the emotional reality experienced by the user." },
  { q: "Why avoid traditional benchmark comparisons?", a: "Because spatial intelligence cannot be measured by a standardized test score. The true benchmark is real-world utility: did the system reduce the user's cognitive load? Did it keep them safe? Did it respect their privacy?" },
  { q: "What is 'Intent Dynamics™'?", a: "It is our framework for modeling how a user's goals change over time. It acknowledges that human intent is fluid—a user might start a journey looking for speed, but shift to looking for scenery based on a change in the environment." },
  { q: "How do you handle conflicting intents?", a: "When a user's historical preferences conflict with their current environmental context, our Explainable AI research dictates that the system should present the conflict to the user and offer a transparent choice, rather than guessing silently." },
  { q: "What is the most difficult spatial problem you are researching?", a: "Inferring intent from minimal data without violating privacy. It requires exceptionally sophisticated contextual modeling to understand what a user wants without actually watching what they do." },
  { q: "How can other developers participate?", a: "Through the Rheole Developer Platform. We expose our research findings as experimental APIs, allowing the global developer community to build upon our spatial models and contribute to the ecosystem." }
    ]
  },
  {
    id: "section-2",
    title: "API References FAQs",
    questions: [

  { q: "Where should I start?", a: "Start with the Authentication and Versioning guides. Understanding how to securely construct a request and pin your API version is fundamental before interacting with any specific resource." },
  { q: "How are endpoints organised?", a: "Endpoints are organised around RESTful, resource-oriented architecture. URLs map to logical entities (e.g., /v1/places, /v1/events) rather than actions." },
  { q: "How do I migrate versions?", a: "We release API versions using a date-based format (YYYY-MM-DD). You can upgrade versions via the Developer Dashboard, which will provide a detailed migration guide for any breaking changes." },
  { q: "What resources require authentication?", a: "Every single resource in the Rheole platform requires authentication. There are no completely public endpoints. Unauthenticated requests will immediately return a 401 Unauthorized." },
  { q: "How do SDKs relate to REST APIs?", a: "Our SDKs (TypeScript, Python, Go, iOS, Android) are idiomatic wrappers around the REST APIs. They handle authentication, retries, and pagination automatically. We strongly recommend using SDKs over raw REST calls." },
  { q: "How are realtime resources documented?", a: "Realtime resources (WebSockets) are documented alongside their REST equivalents, clearly indicating the subscription message formats and expected event payloads." },
  { q: "How do I discover related endpoints?", a: "Our Reference Graph automatically injects 'Related Resources' links at the bottom of every endpoint page. Furthermore, our Semantic API Discovery search allows you to search by intent (e.g., 'find traffic') to locate the correct endpoint." },
  { q: "What is the rate limit?", a: "Rate limits are bound to your Project tier. The standard tier allows 1,000 requests per minute. Limits are returned dynamically in the HTTP response headers (X-RateLimit-Limit)." },
  { q: "Are SDKs auto-generated?", a: "No. While our OpenAPI specs are generated from code, our SDKs are hand-crafted by engineers to ensure they feel idiomatic and natural for the target programming language." },
  { q: "What happens if a request fails?", a: "Review the 'Error Model' section. Every error returns a standardized JSON payload containing a human-readable message, a specific error code, and often a 'recovery_suggestion' string." },
  { q: "How do I report a bug in the documentation?", a: "Every reference page has a 'Provide Feedback' button at the bottom. We treat documentation bugs with the same severity as platform outages." },
  { q: "Can I download the OpenAPI spec?", a: "Yes, the complete OpenAPI 3.1 specification is available for download, allowing you to generate your own clients or import the collection into tools like Postman or Insomnia." },
  { q: "How long are old API versions supported?", a: "We guarantee support for all API versions for a minimum of 24 months after they have been superseded by a newer version." },
  { q: "What is 'Expansion'?", a: "Expansion allows you to request nested relationships within a single API call. Instead of fetching a Place, and then making a second call to fetch its associated Business, you can request '?expand=business' to retrieve both simultaneously." },
  { q: "How do I test my integration safely?", a: "Every Account includes isolated 'Test Mode' Projects. Requests made using Test API Keys will never impact production data or incur billing charges." }
    ]
  },
  {
    id: "section-3",
    title: "Case Studies FAQs",
    questions: [

  { q: "Why are these case studies exploratory?", a: "We believe in asking the right questions before engineering solutions. Exploratory case studies allow us to rigorously define a problem space—understanding the human and spatial nuances—before we commit to a specific technological approach." },
  { q: "How are research questions selected?", a: "Questions emerge from continuous observation of urban friction. Our interdisciplinary team of data scientists, urban planners, and behavioural psychologists identify patterns of frustration or missed opportunity in how people interact with their environments." },
  { q: "Can the public contribute ideas?", a: "Yes. We believe that the best insights often come from the people living the experience. We actively host 'Spatial Inquiry' workshops and maintain open channels for community-driven research proposals." },
  { q: "Do case studies become products?", a: "Not directly, but they inform everything we build. A case study acts as a compass. The insights generated often evolve into core capabilities within the Rheole platform, shaping how our APIs and SDKs are designed." },
  { q: "How do you validate hypotheses?", a: "Through a combination of ethical data simulation, opt-in field studies, and partnerships with academic institutions. We prioritise rigorous, real-world testing over theoretical modelling." },
  { q: "Why avoid exaggerated metrics?", a: "Because spatial intelligence is complex. Claiming a '500% increase in happiness' is marketing fiction. We prefer intellectual honesty, acknowledging both the successes and the profound limitations of our research." },
  { q: "What is 'Spatial Inquiry™'?", a: "It is our proprietary methodology for investigating real-world challenges. It requires examining a problem through three lenses simultaneously: the physical environment, the digital layer, and human intent." },
  { q: "How do you protect privacy during field studies?", a: "Privacy is foundational. We employ edge-processing, aggressive data anonymisation, and strict opt-in protocols. Our research focuses on aggregate spatial rhythms, not individual tracking." },
  { q: "Are these studies limited to major cities?", a: "While dense urban environments provide rich data, our research explicitly includes suburban, rural, and developing regions. Spatial friction exists everywhere, and our solutions must be universally applicable." },
  { q: "What role do urban planners play at Rheole?", a: "They are integral. We cannot understand spatial intelligence without understanding the physical built environment. Urban planners ensure our digital solutions respect and enhance the physical architecture of a city." },
  { q: "How does weather data impact your research?", a: "Profoundly. Weather is the ultimate dynamic modifier of spatial behaviour. Understanding how a sudden downpour changes intent is crucial for building truly ambient, responsive systems." },
  { q: "Why focus on 'decision fatigue'?", a: "Because modern digital mapping provides endless options without context. We research how to reduce cognitive load by offering fewer, but highly relevant, suggestions based on real-time spatial conditions." },
  { q: "How do you define 'Ambient Communities'?", a: "These are latent networks of people with shared interests who occupy the same physical space but are unaware of each other. Our research explores how to safely make these connections visible." },
  { q: "What is the 'Urban Insight Framework™'?", a: "It is our structured method for analysing the relationship between environmental factors (like noise, light, and density) and human decision-making in physical spaces." },
  { q: "Do you study the negative impacts of technology?", a: "Absolutely. A core part of our research is understanding how poorly designed spatial technology can cause harm, such as algorithmic gentrification or distraction-induced accidents." },
  { q: "How do 'Open Questions™' guide your roadmap?", a: "Open Questions are unresolved challenges that we publicly commit to investigating. They act as a transparent research agenda, inviting collaboration from the broader scientific and engineering communities." },
  { q: "What does 'Context over convenience' mean?", a: "It is a research principle stating that the fastest or easiest route is not always the best. A truly intelligent system considers the emotional and environmental context of a journey, not just the math." },
  { q: "How do you measure 'Atmospheric Context'?", a: "We synthesize multiple data streams—including aggregated foot traffic, ambient noise levels, and temporal rhythms—to infer the 'vibe' or atmosphere of a specific location at a specific time." },
  { q: "Can spatial intelligence improve accessibility?", a: "Yes. It is a major research focus. By moving away from static accessibility data and toward dynamic, real-time inference (detecting temporary obstacles), we can significantly improve navigation for differently-abled users." },
  { q: "How can I stay updated on Rheole Research?", a: "Our Case Studies page is continuously updated. We also publish detailed findings in our Engineering Notes and Research Blog, and we frequently present at major urban computing conferences." }
    ]
  },
  {
    id: "section-4",
    title: "Cookies FAQs",
    questions: [

  { q: "What exactly are cookies?", a: "Cookies are small text files placed on your device by the websites you visit. They are widely used to make websites work, or work more efficiently, as well as to provide essential information to the site owners." },
  { q: "Do I have to accept all cookies?", a: "No. You are only required to accept 'Essential' and 'Security' cookies, which are necessary for the website to function. All other categories are entirely optional." },
  { q: "Can I delete cookies later?", a: "Yes. You can delete all cookies already on your device and configure most modern browsers to prevent them from being placed in the future." },
  { q: "Will disabling cookies break the website?", a: "Disabling optional cookies (like Performance or Functional) will not break the website, though you may lose some personalized features. Disabling Essential cookies at the browser level will prevent you from logging in or using the Developer Platform." },
  { q: "How long do cookies remain on my device?", a: "It depends on the type. 'Session cookies' are deleted the moment you close your browser. 'Persistent cookies' remain until they reach their explicitly defined expiration date or you manually delete them." },
  { q: "Does Rheole use cookies for advertising?", a: "No. Rheole does not use advertising or cross-site tracking cookies. We do not sell your data to data brokers or third-party advertising networks." },
  { q: "Can I change my preferences at any time?", a: "Yes. You can access the 'Cookie Preferences' link at the bottom of any page to instantly update your choices. Changes take effect immediately." },
  { q: "What happens when a cookie expires?", a: "Once a cookie passes its expiration date, your browser automatically deletes it. The website will treat you as a new visitor for the purpose that specific cookie served." },
  { q: "Are cookies safe?", a: "Cookies themselves are plain text files. They cannot execute code or deliver viruses. However, because they can be used to track behavior, their safety depends on the transparency and integrity of the website issuing them." },
  { q: "Why do I see cookies from other domains?", a: "These are 'third-party cookies'. On Rheole, these are strictly limited to secure authentication providers (like GitHub) and essential infrastructure monitoring. We do not permit third-party advertising domains." },
  { q: "What is 'Local Storage'?", a: "Local Storage is a modern browser feature similar to a cookie, but it can hold more data and isn't automatically sent to the server with every HTTP request. We use it to save UI preferences like Dark Mode." },
  { q: "Do cookies collect personal data?", a: "Most of our cookies collect anonymous identifiers (like a randomized string). However, Authentication cookies do link to your personal account to keep you securely logged in." },
  { q: "How often is this policy updated?", a: "We review this policy quarterly or whenever we introduce a new feature that requires a change in how we process local storage and cookies." },
  { q: "Who can I contact about privacy concerns?", a: "You can reach our privacy team directly through the Contact page, or by reviewing our full Privacy Architecture documentation." },
  { q: "Is this policy globally applicable?", a: "Yes. While specific regional laws (like GDPR or CCPA) require different disclosures, we apply our strictest privacy standards globally to all users, regardless of their location." }
    ]
  },
  {
    id: "section-5",
    title: "Developer Support FAQs",
    questions: [

  { q: "Where should I ask technical questions?", a: "For general implementation advice, our Developer Forums are best. For account-specific or critical API failures, use the Developer Support ticket system in your dashboard." },
  { q: "How quickly does support respond?", a: "Email support typically responds within 24 hours. Enterprise partners with dedicated SLAs receive prioritized routing." },
  { q: "When should I contact enterprise support?", a: "Enterprise support is designed for large-scale deployments, custom SLA requirements, complex legal compliance reviews, and dedicated Technical Account Management." },
  { q: "How do I report a bug?", a: "You can submit bug reports directly through your Developer Portal or via our public GitHub repositories if the bug is related to an open-source SDK." },
  { q: "How do I request a feature?", a: "Feature requests can be submitted via the Community Forums under the 'Feedback' category, where other developers can upvote your idea." },
  { q: "How do I report a security issue?", a: "Please practice responsible disclosure by emailing security@rheole.com. Do not post potential vulnerabilities in public channels." },
  { q: "How do I follow platform incidents?", a: "You can view real-time telemetry at our Status Page and subscribe via Email, SMS, or Slack Webhook for instant incident alerts." },
  { q: "What information should I include in a ticket?", a: "Always include the exact API endpoint, the HTTP status code, a snippet of the request payload, and most importantly, the 'x-rheole-request-id' response header." },
  { q: "Can someone review my application architecture?", a: "Yes. Enterprise partners have access to Architecture Clinics. For independent developers, we encourage posting architectural drafts in the Community Forums." },
  { q: "Is the AI Assistant trained on my code?", a: "No. The AI Assistant is trained exclusively on Rheole's public documentation, SDK source code, and knowledge base. It does not ingest your proprietary queries for training." },
  { q: "Do you offer live chat support?", a: "Live chat is currently available exclusively for Enterprise partners during critical deployment windows." },
  { q: "Where can I find older versions of the SDK?", a: "All historical versions of our SDKs are maintained on npm, Maven Central, and CocoaPods. You can find version-specific documentation in the Developer Portal archive." },
  { q: "How do I appeal an API rate limit block?", a: "If your account was blocked due to an unexpected spike, contact Developer Support with an explanation of the traffic surge and your requested limit increase." },
  { q: "Are Office Hours recorded?", a: "Yes. All bi-weekly Office Hours are recorded and uploaded to our Video Tutorials library within 48 hours of the broadcast." },
  { q: "Can I get help with a third-party integration?", a: "We provide best-effort guidance for integrating Rheole with popular frameworks (like Next.js or React Native). For obscure or proprietary frameworks, we recommend the Community Forums." },
  { q: "What is a 'Living Knowledge Base'?", a: "It means our documentation is never 'finished'. Every time a developer asks a novel question that isn't covered in the docs, we update the docs to include that context for the next person." },
  { q: "How do I recover a lost Developer Key?", a: "For security reasons, Developer Keys cannot be recovered. If you lose a key, you must immediately revoke it in the Developer Portal and generate a new one." },
  { q: "Do you provide hands-on coding assistance?", a: "We provide detailed examples and integration guidance, but we do not write custom application logic for your specific business requirements." },
  { q: "How are breaking changes communicated?", a: "Breaking changes are announced via email to all active developers 90 days in advance, accompanied by a detailed Migration Guide in the Knowledge Base." },
  { q: "Is the community actively moderated?", a: "Yes. Our Developer Advocates actively moderate the forums to ensure discussions remain productive, respectful, and technically accurate." }
    ]
  },
  {
    id: "section-6",
    title: "Help Center FAQs",
    questions: [

  { q: "How does Rheole know what to recommend?", a: "We use Contextual Intelligence. The platform analyzes the time of day, current weather, venue operating hours, and your anonymized historical routine to provide recommendations that actually make sense for the moment." },
  { q: "Can I disable location tracking?", a: "Yes. You can use Rheole by manually entering locations for searches and routing. However, ambient features like live transit updates and nearby community alerts require background location access." },
  { q: "How are communities discovered?", a: "Communities are geographically anchored. You discover them by being in or verifying your residency in specific neighborhoods, ensuring groups remain hyper-local and relevant." },
  { q: "What makes Smart Routing different?", a: "Smart Routing doesn't just calculate distance. It factors in live transit delays, elevation changes for cyclists, pedestrian safety data, and current weather conditions to find the optimal path." },
  { q: "How does Context work?", a: "Context is the layer that sits between your search and the map. If you search 'coffee' at 8 AM, Context prioritizes fast espresso bars. At 8 PM, it prioritizes cozy cafes open late." },
  { q: "Can I customise recommendations?", a: "Absolutely. In your Account Settings, you can define strict dietary requirements, accessibility needs, and pricing preferences that will universally filter all your recommendations." },
  { q: "How do I report an incorrect map location?", a: "Tap the location pin, scroll to the bottom of the venue card, and select 'Suggest an Edit'. Our moderation team reviews these within 24 hours." },
  { q: "What happens if I lose internet connection?", a: "If you have 'Offline Regions' enabled in your settings, your active routes, saved places, and neighborhood maps will remain fully functional without cellular data." },
  { q: "How do I change my home or work address?", a: "Navigate to Account > Preferences > Saved Locations. Here you can update, add, or remove your primary anchor points." },
  { q: "Are my saved places public?", a: "No. By default, all saved places and custom lists are entirely private. You must explicitly generate a shareable link to show them to friends." },
  { q: "How do I turn off specific notifications?", a: "Go to Settings > Notifications. You have granular control—you can disable 'Community Updates' while keeping 'Transit Delays' active." },
  { q: "Why is a route marked as 'Potentially Unsafe'?", a: "Rheole integrates with local municipal data. A route may be flagged if there is active construction, severe weather flooding, or inadequate street lighting reported in the area." },
  { q: "Can I use Rheole in a new city?", a: "Yes. When you travel, Rheole automatically detects the new region and begins caching local transit schedules and highly-rated venues to ensure a seamless experience." },
  { q: "How do I delete my account?", a: "Go to Account > Privacy & Security > Danger Zone. Selecting 'Delete Account' initiates a cryptographic scrub of your data, completed within 30 days." },
  { q: "What is the 'Routine Cache'?", a: "It is an encrypted, on-device ledger of your frequent geographic movements. It helps Rheole predict when you might need transit times to work or home." },
  { q: "Why did my community request get denied?", a: "Community moderators set their own entrance criteria. Often, this requires a verified profile or a brief introduction message. Check the community guidelines." },
  { q: "How do I switch to dark mode?", a: "Go to Settings > Theme. You can select Light, Dark, or System, which automatically matches your device's current OS setting." },
  { q: "Can I share a live route with a friend?", a: "Yes. Once navigation has started, swipe up on the bottom card and tap 'Share ETA'. This generates a secure, temporary tracking link." },
  { q: "How do I change the language?", a: "Language preferences are managed in Settings > Language & Region. Changing this updates both the UI and the spoken navigation instructions." },
  { q: "What does 'Anonymized Telemetry' mean?", a: "It means we collect diagnostic data (like app crashes or slow load times) without attaching your name, email, or exact location to the report." },
  { q: "How do I contact a business directly?", a: "If a business has provided contact details, a 'Call' or 'Message' button will appear directly beneath their opening hours on their venue card." },
  { q: "Why isn't my route showing public transit?", a: "Ensure 'Transit' is toggled on in your mobility preferences. If it is, the local transit authority may be experiencing a complete blackout or we may not support that specific region yet." },
  { q: "Can I review a place anonymously?", a: "To prevent spam and manipulation, all reviews require a verified Rheole account. However, you can choose to display only your first name in Privacy Settings." },
  { q: "How do I view my offline maps?", a: "Go to Account > Offline Regions. Here you can see downloaded areas, update them over Wi-Fi, or delete them to free up device storage." },
  { q: "Where do I report a bug with the app?", a: "In the Help Center, scroll to 'Contact Support' and select 'Report a Bug'. Including a screenshot and your device model greatly accelerates our fix." }
    ]
  },
  {
    id: "section-7",
    title: "Trust Center FAQs",
    questions: [

  { q: "How does Rheole protect user data?", a: "We employ a combination of strict data minimisation at the edge, AES-256 encryption at rest, and TLS 1.3 in transit. Furthermore, our systems are designed so that personally identifiable information is abstracted before reaching our central processing clusters." },
  { q: "How does AI make recommendations?", a: "Our AI utilizes contextual spatial graphs, analyzing macro-scale patterns rather than tracking individual users. We enforce strict explainability protocols, ensuring algorithms can justify the logic behind their outputs." },
  { q: "How is trust evaluated internally?", a: "Through our Confidence Framework™, a mandatory review process that requires every engineering decision to be vetted by our Security, Privacy, and AI Ethics boards prior to deployment." },
  { q: "What happens during a security incident?", a: "Our automated incident response protocols immediately isolate affected infrastructure. We then communicate openly via our Status Page, followed by a deeply technical, public post-mortem once the issue is fully resolved." },
  { q: "Can I delete my information?", a: "Absolutely. We provide automated, verifiable deletion pipelines. When requested, data is cryptographically scrubbed from primary databases and all backup archives within a strict 30-day window." },
  { q: "How is privacy maintained in Urban Computing?", a: "Urban Computing initiatives rely exclusively on anonymized, aggregated datasets. We study macro-scale mobility patterns (like traffic flow) and strictly prohibit the isolation or tracking of individual devices." },
  { q: "How are vulnerabilities reported?", a: "Security researchers can participate in our Coordinated Disclosure program by emailing encrypted reports to security@rheole.com. We provide rapid triage, remediation, and bounty recognition." },
  { q: "How does Rheole approach responsible AI?", a: "Through our Responsible Intelligence™ framework, which mandates algorithmic explainability, continuous bias reduction testing, and strict human oversight for all high-stakes model updates." },
  { q: "How are platform outages communicated?", a: "Outages are broadcasted instantly via our live Status Page telemetry. Developers can also subscribe to RSS feeds, SMS alerts, or automated Slack webhooks for real-time degradation alerts." },
  { q: "How do policies evolve?", a: "Through Living Governance™. As technology and global regulations advance, we update our policies proactively, maintaining a clear, version-controlled public ledger of all changes." },
  { q: "Does Rheole sell my data?", a: "Never. Rheole does not sell data, nor do we use spatial intelligence to build advertising profiles. Our business model is entirely focused on providing premium developer infrastructure." },
  { q: "Are third-party audits conducted?", a: "Yes. We undergo rigorous continuous vulnerability scanning and conduct annual penetration testing with elite third-party security firms." },
  { q: "Who owns the data generated by my application?", a: "You do. Enterprise and developer data processed through the Rheole API remains the exclusive property of the developer and is not used to train our foundational models." },
  { q: "What is the Transparency Graph™?", a: "It is our architectural philosophy of linking related policies, live status, security updates, and research into a single, cohesive hub rather than hiding them in isolated legal footers." },
  { q: "How do you ensure AI fairness?", a: "By continuously auditing our training sets against diverse geographical, cultural, and socio-economic baselines to prevent localized biases from skewing spatial recommendations." },
  { q: "What encryption standards are used?", a: "AES-256 for all data at rest, and TLS 1.3 with Perfect Forward Secrecy for all data traversing our networks." },
  { q: "Is Rheole SOC 2 compliant?", a: "We are currently undergoing our formal SOC 2 Type II observation period, with our compliance architecture built to exceed those baseline requirements." },
  { q: "How long is data retained?", a: "Data is retained only for as long as strictly necessary to fulfill the immediate API request, unless you explicitly configure longer retention policies within your Developer Portal." },
  { q: "Do you have a Bug Bounty program?", a: "Yes, we collaborate closely with independent security researchers, providing competitive bounties for responsibly disclosed vulnerabilities." },
  { q: "How do you handle government data requests?", a: "We require valid, legally binding subpoenas. Due to our strict data minimisation and cryptographic abstraction, we often possess mathematically zero identifying information to hand over." },
  { q: "Can I self-host Rheole infrastructure?", a: "Rheole currently operates exclusively as a globally distributed cloud API to ensure continuous security patching and real-time model updates." },
  { q: "What is Privacy by Design?", a: "It is the engineering practice of building privacy controls into the core architecture of the software, rather than bolting them on as an afterthought for compliance." },
  { q: "How are developer keys secured?", a: "Developer API keys are hashed securely and never stored in plaintext. We provide automated key-rotation tools and anomaly detection to prevent credential abuse." },
  { q: "What constitutes a 'Trust Resource'?", a: "Any documentation, policy, live dashboard, or research publication that provides developers and users with factual insight into how Rheole operates." },
  { q: "Why is Trust a central pillar?", a: "Because Ambient Spatial Intelligence requires deep integration into physical spaces. If people do not trust the infrastructure, the technology cannot ethically exist." }
    ]
  },
  {
    id: "section-8",
    title: "Urban Computing FAQs",
    questions: [

  { q: "Does Rheole track individual people?", a: "No. Our philosophy is built on absolute privacy. We study the aggregated 'pulse' of the city—how crowds move, how traffic flows, how weather changes—not the specific trajectory of any single individual. We use advanced edge-processing and differential privacy to ensure individual anonymity." },
  { q: "What is a 'Living City'?", a: "A living city is a conceptual framework that views a city as a biological organism rather than a mechanical grid. It acknowledges that a city is constantly evolving, reacting to stimuli (like rain or festivals), and changing its character based on the time of day." },
  { q: "Why focus on Bengaluru?", a: "Bengaluru is one of the most dynamic, rapidly evolving, and spatially complex cities in the world. It provides an incredibly rich testing ground for Urban Computing, featuring extreme traffic density, diverse micro-cultures, and rapid infrastructure changes." },
  { q: "How is this different from 'Smart City' initiatives?", a: "Traditional Smart City initiatives often focus on operational efficiency for governments (e.g., optimizing traffic lights via surveillance). Rheole's Urban Computing focuses on human understanding—providing citizens with the context they need to navigate their lives, without the surveillance." },
  { q: "What data does Rheole actually use?", a: "We synthesize public information (transit schedules, event registries), environmental sensors (weather, air quality), and aggregated, heavily anonymized mobility patterns. We do not use personal identifiable information (PII)." },
  { q: "How do you handle unpredictable events?", a: "Unpredictability is exactly why static maps fail. Our 'Environmental Layer' and 'Mobility Layer' are designed to detect sudden anomalies (like a flooded street) in real-time through aggregate movement shifts, allowing the system to react instantly." },
  { q: "Why is 'Neighbourhood Identity' important?", a: "Because treating all areas of a city equally leads to terrible routing and recommendations. A residential street requires a different digital approach than a commercial high street. Understanding identity preserves local culture." },
  { q: "Can Urban Computing help small businesses?", a: "Yes. By focusing on physical reality (foot traffic, local relevance) rather than digital reality (SEO, paid reviews), we can surface high-quality, local businesses that are often buried by global search algorithms." },
  { q: "What is the 'Urban Pulse'?", a: "It is our proprietary metric for measuring the 'liveliness' of a specific area at a specific time. It combines factors like foot traffic density, noise levels, and the concentration of open businesses to determine the area's current atmosphere." },
  { q: "How does Urban Computing improve accessibility?", a: "By moving away from static, often outdated accessibility data. We research how to use aggregated movement patterns to infer temporary obstacles (like broken elevators or construction), providing real-time, dynamic accessibility routing." },
  { q: "Does this research dictate how people should live?", a: "Absolutely not. The goal is to provide deep context so people can make their own informed decisions. We aim to augment human agency, not restrict it." },
  { q: "How do you prevent algorithmic gentrification?", a: "This is a core research question. We are extremely careful to ensure our 'discovery' algorithms do not artificially funnel wealth to specific areas while neglecting others. We prioritize diverse, equitable spatial representation." },
  { q: "What is the 'City Memory'?", a: "It is our framework for understanding how a city changes over long time horizons. It allows the system to know that a specific park floods every monsoon, or that a specific street becomes a vibrant market every Diwali." },
  { q: "How does weather affect your models?", a: "Weather is a primary modifier. We don't just display the temperature; we model how rain will slow traffic, increase demand for public transport, and empty outdoor public spaces, adjusting our recommendations accordingly." },
  { q: "Why avoid the term 'IoT' (Internet of Things)?", a: "Because IoT implies a focus on hardware and sensors. While sensors exist, our focus is on the human intelligence extracted from the data, not the physical hardware collecting it." },
  { q: "Is this technology only for the wealthy?", a: "No. Better public transit routing, safer walking paths, and improved emergency responses benefit everyone. We explicitly design our research to ensure spatial intelligence serves all demographics equitably." },
  { q: "How do urban planners use this data?", a: "Through our 'Urban Cognition' research, we provide planners with anonymized insights into how citizens actually use public spaces, allowing them to design more effective, human-centric infrastructure." },
  { q: "What happens during a massive festival?", a: "The standard 'Mobility Layer' is temporarily suspended, and the 'Cultural Layer' takes precedence. The system understands that roads are now pedestrian zones and routes users accordingly." },
  { q: "Can this system work offline?", a: "Parts of it can. While real-time context requires connectivity, the 'City Memory' and fundamental 'Neighbourhood Identity' are cached locally on the edge device to ensure basic navigation remains possible." },
  { q: "Where can I read your published research?", a: "Our findings on privacy-preserving spatial modelling and urban dynamics are regularly published on the Rheole Research Blog and presented at global urban computing conferences." }
    ]
  },
];
